development:
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  database: formats_development

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5
  database: formats_test
